services:
  nats:
    image: nats:alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    command: -js -m 8222
    profiles:
      - default
      - test
  scheduler:
    build:
      context: scheduler
      dockerfile: Dockerfile
    depends_on:
      - nats
    ports:
      - "8080:8080"
    env_file:
      - dev.env
    extra_hosts:
      host.docker.internal: host-gateway
    environment:
      - NATS_ADDR=nats://nats:4222
    profiles:
        - default