## This is a minimal values file for the elvia-deployment chart.
## An example of all possible usages can be found here:
## https://github.com/3lvia/kubernetes-charts/blob/master/elvia-deployment/values.yaml

name: scheduler
namespace: ice
microserviceType: webapi

replicaCount: 1

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  port: 80
  targetPort: 8080

env:
  - name: ENVIRONMENT
    value: dev
  - name: API_ADDR
    value: :8080
  - name: NATS_ADDR
    value: nats://nats.ifsweeklyplanner:4222
  - name: OTEL_LOG_LEVEL
    value: debug
  - name: VAULT_ADDR
    value: https://vault.dev-elvia.io
  - name: ROLE
    value: "scheduler"
  - name: MOUNT_PATH
    value: "kubernetes/runtimeservice/ice/scheduler"

## Subdomains are created in https://github.com/3lvia/dns-terraform.
## The CLI does not currently support creating subdomains automatically.
# ingress:
#   subdomain: my-subdomain
#   path: "/"

#readinessProbe:
#  failureThreshold: 3
#  httpGet:
#    path: /health
#    port: 8080
#    scheme: HTTP
#  initialDelaySeconds: 15
#  periodSeconds: 15
#  successThreshold: 1
#  timeoutSeconds: 3
#
#livenessProbe:
#  failureThreshold: 5
#  httpGet:
#    path: /health
#    port: 8080
#    scheme: HTTP
#  initialDelaySeconds: 15
#  periodSeconds: 15
#  successThreshold: 1
#  timeoutSeconds: 3
#
#startupProbe:
#  failureThreshold: 30
#  httpGet:
#    path: /health
#    port: 8080
#    scheme: HTTP
#  initialDelaySeconds: 15
#  periodSeconds: 3
#  successThreshold: 1
#  timeoutSeconds: 2