name: scheduler.go test

on:
  push:
    branches: [trunk]
    paths:
      - '.github/workflows/scheduler-go-test.yml'
      - 'scheduler.go/**/*.go'
      - 'scheduler.go/go.mod'
      - 'scheduler.go/go.sum'
  pull_request:
    branches: [trunk]
    paths:
      - '.github/workflows/scheduler-go-test.yml'
      - 'scheduler.go/**/*.go'
      - 'scheduler.go/go.mod'
      - 'scheduler.go/go.sum'

env:
  PATH: 'scheduler.go'

jobs:
  analyze:
    name: Analyze
    runs-on: elvia-runner
    permissions:
      actions: read
      contents: read
      security-events: write
    # Limits the number of concurrent runs of this job to one, and cancels any in progress.
    concurrency:
      group: '${{ github.workflow }}-${{ github.ref }}-analyze'
      cancel-in-progress: true
    steps:
      - uses: 3lvia/core-github-actions-templates/analyze@trunk
        with:
          # This can be set to a more specific path if you want to analyze only a part of the repository.
          working-directory: ${{ env.PATH }}
          language: 'go'

  test:
    name: Test
    runs-on: elvia-runner
    strategy:
      matrix:
        go-version: [ '1.23.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: ${{ env.PATH }}/go.sum
      - name: Test with Go
        run: |
          cd ${{ env.PATH }}
          go test -v ./... -json > TestResults-${{ matrix.go-version }}.json
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-${{ matrix.go-version }}
          path: ${{ env.PATH }}/TestResults-${{ matrix.go-version }}.json