name: Service Build and release

on:
  push:
    branches: [trunk]
    paths:
      - 'scheduler/**'
  pull_request:
    branches: [trunk]
    paths:
      - 'scheduler/**'

env:
  SYSTEM_NAME: 'ice'
  APPLICATION_NAME: 'scheduler'
  PROJECT_FILE: 'scheduler/go.mod'
  HELM_VALUES_FILE: '.github/deploy/svc-values.yml'

jobs:
  analyze:
    name: Analyze
    runs-on: elvia-runner
    permissions:
      actions: read
      contents: read
      security-events: write
    # Limits the number of concurrent runs of this job to one, and cancels any in progress.
    concurrency:
      group: '${{ github.workflow }}-${{ github.ref }}-analyze'
      cancel-in-progress: true
    steps:
      - uses: 3lvia/core-github-actions-templates/analyze@trunk
        with:
          # This can be set to a more specific path if you want to analyze only a part of the repository.
          working-directory: 'scheduler/'
          language: 'go'

  build-scan:
    name: Build and Scan
    runs-on: elvia-runner
    permissions:
      actions: read
      contents: write
      id-token: write
      pull-requests: write
      security-events: write
    # Limits the number of concurrent runs of this job to one, and cancels any in progress.
    concurrency:
      group: '${{ github.workflow }}-${{ github.ref }}-build-scan'
      cancel-in-progress: true
    environment: build
    steps:
      - uses: 3lvia/core-github-actions-templates/build@trunk
        with:
          name: ${{ env.APPLICATION_NAME }}
          namespace: ${{ env.SYSTEM_NAME }}
          project-file: ${{ env.PROJECT_FILE }}
          trivy-upload-report: 'true'
          trivy-post-comment: 'true'
          AZURE_CLIENT_ID: ${{ vars.ACR_CLIENT_ID }}